name: rsna_2021_demo
channels:
  - defaults
  - pytorch
dependencies:
  - pip=20.1.1
  - python=3.7.3
  - pytorch=1.8.0
  - python-blosc==1.7.0
  - torchvision=0.9.0
  - pip:
      - azure-mgmt-resource==12.1.0
      - azureml-contrib-dataset==1.34.0      
      - azure-mgmt-datafactory==1.1.0
      - azureml-mlflow==1.32.0
      - azureml-sdk==1.32.0
      - azureml-tensorboard==1.32.0
      - azureml-widgets==1.34.0
      - ipykernel==6.3.1
      - jupyter==1.0.0
      - jupyter-client==6.1.5
      - lightning-bolts==0.3.4
      - matplotlib==3.3.0
      - mlflow==1.17.0
      - mypy==0.812
      - numba==0.51.2
      - numpy==1.19.1
      - numba==0.51.2
      - medcam==0.1.21
      - opencv-python-headless==4.5.1.48
      - pandas==1.1.0
      - param==1.9.3
      - pillow==8.2.0
      - pydicom==2.0.0
      - scikit-image==0.17.2
      - scikit-learn==0.23.2
      - scipy==1.5.2
      - seaborn==0.10.1
      - simpleitk==1.2.4
      - six==1.15.0
      - tabulate==0.8.7
      - tensorboard==2.3.0
      - tensorboardX==2.1
      - torchprof==1.3.3
      - torchmetrics==0.4.1
      - torchxrayvision==0.0.31